apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatapp
  template:
    metadata:
      labels:
        app: chatapp
    spec:
      containers:
        - name: chatapp-container
          image: chatapp
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: chatapp-service
spec:
  selector:
    app: chatapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
